# This file was generated by GoReleaser. DO NOT EDIT.
cask "warpdl" do
  name "warpdl"
  desc "The official Warp CLI download manager"
  homepage "https://warpdl.org"
  version "1.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "warpdl"

  on_macos do
    on_intel do
      url "https://github.com/warpdl/warpdl/releases/download/v#{version}/warpdl_#{version}_macOS_amd64.tar.gz"
      sha256 "72a5f4b544e61b593133b2a22cb84dc7f6c73ac35d2dc9b55d9182bfaae4aed0"
    end
    on_arm do
      url "https://github.com/warpdl/warpdl/releases/download/v#{version}/warpdl_#{version}_macOS_arm64.tar.gz"
      sha256 "05d64b5627d26037d4fff7b9ca30eb954a3ac64846ff72dfe804369e4afc8a4f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/warpdl/warpdl/releases/download/v#{version}/warpdl_#{version}_linux_amd64.tar.gz"
      sha256 "eb4f72da261d8e87b9f768fcc09633991e384b4f250994e862fe1ed57a6db498"
    end
    on_arm do
      url "https://github.com/warpdl/warpdl/releases/download/v#{version}/warpdl_#{version}_linux_arm64.tar.gz"
      sha256 "53a9a9a538671ee84ed32a3f77d191d1c70ef550d3882fb900a28fde86a6a170"
    end
  end

  postflight do
    system_command '/usr/bin/xattr', args: ['-d', 'com.apple.quarantine', staged_path/'warpdl']
  end

  # No zap stanza required
end
