# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Warpdl < Formula
  desc "The official Warp CLI download manager"
  homepage "https://github.com/warpdl/warpdl"
  version "1.5.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/warpdl/warpdl/releases/download/v1.5.1/warpdl_1.5.1_macOS_amd64.tar.gz"
      sha256 "a2b79cc9000e706b956e5184ba9e3c5133c7f3aab5b99c6a8a36174eab3fba5a"

      define_method(:install) do
        bin.install "warpdl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/warpdl/warpdl/releases/download/v1.5.1/warpdl_1.5.1_macOS_arm64.tar.gz"
      sha256 "deb6b5948647b40f74b068fe10e97f83bdb1538c62029e98dbb19205817a5d10"

      define_method(:install) do
        bin.install "warpdl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/warpdl/warpdl/releases/download/v1.5.1/warpdl_1.5.1_linux_amd64.tar.gz"
      sha256 "94aa37cd13000504fd9b2339a2ad69d7fd5d7db2a0756527e11e8f95477133f4"
      define_method(:install) do
        bin.install "warpdl"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/warpdl/warpdl/releases/download/v1.5.1/warpdl_1.5.1_linux_armv6.tar.gz"
      sha256 "3b4eabeff90906e990061fe313f7c77c455bdcda7ee7bce9bef875f57c04b84f"
      define_method(:install) do
        bin.install "warpdl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/warpdl/warpdl/releases/download/v1.5.1/warpdl_1.5.1_linux_arm64.tar.gz"
      sha256 "04775775e500b8423347ebc73b8ce433b3bd0a9125dc9afdd779578782b54a9a"
      define_method(:install) do
        bin.install "warpdl"
      end
    end
  end

  def post_install
    # Stop any running daemon from a previous version to ensure clean upgrade
    begin
      system "#{bin}/warpdl", "stop-daemon"
    rescue
      # Daemon wasn't running, that's fine
    end
  end

  def caveats
    <<~EOS
      To start WarpDL daemon now and auto-start at login:
        brew services start warpdl

      To stop the daemon:
        brew services stop warpdl

      To restart after upgrade:
        brew services restart warpdl

      IMPORTANT: Before uninstalling, run:
        brew services stop warpdl
        brew uninstall warpdl
    EOS
  end

  service do
    run [opt_bin/"warpdl", "daemon"]
    keep_alive true
    working_dir var/"warpdl"
    log_path var/"log/warpdl.log"
    error_log_path var/"log/warpdl.log"
  end

  test do
    system "#{bin}/warpdl", "--version"
  end
end
