# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Warpdl < Formula
  desc "The official Warp CLI download manager"
  homepage "https://github.com/warpdl/warpdl"
  version "1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/warpdl/warpdl/releases/download/v1.5/warpdl_1.5_macOS_amd64.tar.gz"
      sha256 "a32f9bdfdbba3b7a0307501b780d861f89cce4478d22fa61227fb492977f86c9"

      define_method(:install) do
        bin.install "warpdl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/warpdl/warpdl/releases/download/v1.5/warpdl_1.5_macOS_arm64.tar.gz"
      sha256 "9b7bc07eb72514471dabc9f622af026f73aa8223783b949d67f6f2a9d0097643"

      define_method(:install) do
        bin.install "warpdl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/warpdl/warpdl/releases/download/v1.5/warpdl_1.5_linux_amd64.tar.gz"
      sha256 "95fa6060cd7f2966461c38791d234d714a8fa202a961d7a9151105b71c0ef7bf"
      define_method(:install) do
        bin.install "warpdl"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/warpdl/warpdl/releases/download/v1.5/warpdl_1.5_linux_armv6.tar.gz"
      sha256 "8d53ad3134a6da93fe19a29f61132b7652c28231aa0a7c174482961fb31fb069"
      define_method(:install) do
        bin.install "warpdl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/warpdl/warpdl/releases/download/v1.5/warpdl_1.5_linux_arm64.tar.gz"
      sha256 "abd10a7957c1629c3eb0b4cbebc9e5366d93baab6f1a75cbae2e9a9abb74d333"
      define_method(:install) do
        bin.install "warpdl"
      end
    end
  end

  def post_install
    # Stop any running daemon from a previous version to ensure clean upgrade
    begin
      system "#{bin}/warpdl", "stop-daemon"
    rescue
      # Daemon wasn't running, that's fine
    end
  end

  def caveats
    <<~EOS
      To start WarpDL daemon now and auto-start at login:
        brew services start warpdl

      To stop the daemon:
        brew services stop warpdl

      To restart after upgrade:
        brew services restart warpdl

      IMPORTANT: Before uninstalling, run:
        brew services stop warpdl
        brew uninstall warpdl
    EOS
  end

  service do
    run [opt_bin/"warpdl", "daemon"]
    keep_alive true
    working_dir var/"warpdl"
    log_path var/"log/warpdl.log"
    error_log_path var/"log/warpdl.log"
  end

  test do
    system "#{bin}/warpdl", "--version"
  end
end
