# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Warpdl < Formula
  desc "The official Warp CLI download manager"
  homepage "https://warpdl.org"
  version "0.0.18"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/warpdl/warp-releases/releases/download/0.0.18/warp_0.0.18_macOS_amd64.tar.gz"
      sha256 "25267eb5039d2f9d672349cb4e775848bba898737b1b6be616f646d4415b5c96"

      def install
        bin.install "warpdl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/warpdl/warp-releases/releases/download/0.0.18/warp_0.0.18_macOS_arm64.tar.gz"
      sha256 "f44761a05b427fa51c543988497c276b7018f025dcf49ee5e73da849ae56dacf"

      def install
        bin.install "warpdl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/warpdl/warp-releases/releases/download/0.0.18/warp_0.0.18_linux_armv6.tar.gz"
      sha256 "5b9391cfc1f92cdaee56296b815618caaf1d634bc203051f534e7c1a4809bb3a"

      def install
        bin.install "warpdl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/warpdl/warp-releases/releases/download/0.0.18/warp_0.0.18_linux_amd64.tar.gz"
      sha256 "14704f1f800471237a8efaca53c97d8f557dbbea785aa5a578c323d9c58ec709"

      def install
        bin.install "warpdl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/warpdl/warp-releases/releases/download/0.0.18/warp_0.0.18_linux_arm64.tar.gz"
      sha256 "082790e93393eb47b38b3362afa9f1cb2309153b78dc7ecad954ceb67adb2c48"

      def install
        bin.install "warpdl"
      end
    end
  end

  test do
    system "#{bin}/warpdl --version"
  end
end
